name: CI - scan and build image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: '45 17 * * 1'
  workflow_dispatch:


permissions:
  contents: read

jobs:
  checkov_scan:
    permissions:
      contents: read 
      security-events: write 
      actions: read 
    runs-on: ubuntu-latest
    name: Run Checkov Code Scan
    environment: PrismaCloudEnv
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - id: code-scan
        name: Checkov GitHub Action
        uses:  bridgecrewio/checkov-action@master
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          api-key: '${{ secrets.secrets.PRISMA_CLOUD_ACCESS_KEY }}::${{ secrets.PRISMA_CLOUD_SECRET_KEY }}'
          directory: '.'
          soft_fail: true
          use_enforcement_rules: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
  
  build:
    runs-on: ubuntu-latest
    name: Build Image and Push to Registry
    environment: DockerEnv
    steps:
    - name: Get short SHA
      run: echo "GHA_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV
          
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Tag and Push Docker images
      uses: docker/build-push-action@master
      with:
        tags: kathywan/log4shell-vulnerable-app:${{ env.GHA_SHA }},kathywan/log4shell-vulnerable-app:latest
        push: true
